### ISSUE TITLE
Create a test app to run jxcore tests on iOS.

### ISSUE THREAD

**Issue by enricogior** [thaliproject/jxcore#30]
A proof of concept has been tested on the iOS simulator.

**Comment by yaronyg** [comment]
Diego should start working on this today.

**Comment by yaronyg** [comment]
There already is something that 'kind of work' that uses a client/server approach. There is a HTTP server that receives requests from the client with test results. The plan is to keep working in that direction. They hope to have things working at a basic level by the end of tomorrow. But they might want to make some changes to optimize the approach to have a simpler test framework. Right now it's complicated because you have a client and a server that are both hosted on the device. We need to decide what is the best architecture. We will try to run everything on iOS 10 using the existing complicated architecture and see if we can find a better approach. We want something that doesn't require manual intervention, today we have to read the result from a web page that is on the tested device.

**Comment by yaronyg** [comment]
We just got the tests started on iOS! 60 tests failing but we suspect this is the same reasons as we saw on Android. So hopefully this should be good. It would also be good to re-run the tool on iOS 9 so we can compare apples to apples.

**Comment by enricogior** [comment]
The test app still need work, but a first run on both iOS 9 and iOS 10 shows identical results.
There are 55 tests the are failing on the simulator that pass on the jailbroken iOS9 device.

**Comment by yaronyg** [comment]
Today they worked on getting rid of the HTTP server so we don't use JXcore to test JXcore.

**Comment by enricogior** [comment]
Building the app from scratch, so far so good, the app is using the jxcore-cordova plugin and it's running on the device. By tomorrow I plan to have the first tests running.

**Comment by enricogior** [comment]
The basic functionality is done, tests are executed loading them at run-time.
We need better encapsulation for each test and several tests needs to properly skip when running on ios.

**Comment by enricogior** [comment]
Test encapsulation works when running each test in a sub-thread.

**Comment by enricogior** [comment]
While running the tests a new jxcore issue was found: https://github.com/thaliproject/jxcore/issues/66
We will find a workaround for the test app if we decide not to fix it right away.

**Comment by enricogior** [comment]
New app in the work that uses the child engine as main instance to run each test in a brand new engine context.

**Comment by yaronyg** [comment]
We did our first actual run but to be fair almost 1/2 the tests are disabled because of a variety of bugs and problems we have to work through.

**Comment by enricogior** [comment]
We have the code components working, we still need to add a minimum UI and clean-up a few things (the project needs to be added to the JXcore repo and to import the test files from the test folder, while currently it is a standalone project with a private copy of the test files).
In regard to the test results: we are down to 1/3 of tests disabled or not working. 10 tests are failing for the same reason (file pipe), 2 are failing for reasons we haven't investigated yet, 1 crash, 1 random crash.

**Comment by enricogior** [comment]
The has been committed to a dedicated branch, we will add it to the master after finishing the investigation of the failing tests.
https://github.com/thaliproject/jxcore/commits/orangemocha-ios-testapp

**Comment by enricogior** [comment]
Test report:
https://github.com/thaliproject/jxcore/wiki/iOS-test-report-for-JXcore-0.3.1.8
