### ISSUE TITLE
test.js script returns different results compared to test.py

### ISSUE THREAD

**Issue by enricogior** [thaliproject/jxcore#41]
The test/test.js script's main purpose is to run tests on platform that don't have python, such iOS and Android.
On desktop it should also work and return the same results returned by running the tests using the python script tools/test.py, but it currently doesn't.
Several tests fails on macOS when run using test.js.

**Comment by enricogior** [comment]
Most of the tests were failing because the common.tmpDir they write to was not present or already contained a file that the tests use.
One test is still failing on macOS, I've opened a new issue to track the problem https://github.com/thaliproject/jxcore/issues/47 but it's not so urgent to block the current fix.

**Comment by enricogior** [comment]
PR submitted https://github.com/thaliproject/jxcore/pull/48

**Comment by yaronyg** [comment]
This is fixed for all the tests but one. Tests.js invokes all the individual jxcore tests directly and because of that some tests were failing because they were expecting a temp directory that only test.py was creating. We had to make sure that the directory exists and is empty. This fixed 10 broken tests but on Mac there is still 1 test that fails when it is run using test.js. If you run it directly using jx it passes. It seems that the child process is somehow blocking the test due to too many iterations. It uses 1000 iterations it fails but if you set to 100 iterations it passes. It is not blocking anyone so we have opened a specific bug for the issue and we can commit this fix.
